### ISSUE TITLE
Is d_adsrc data source ID or Advertiser ID?

### ISSUE THREAD

**Issue by weijiejane** [AdobeDocs/audience-manager.en#1]
Issue in help/using/integration/media-data-integration/click-data-pixels.md
Here it says d_adsrc is data source ID, but on another reference
https://docs.adobe.com/content/help/en/audience-manager/user-guide/implemenation-integration-guides/media-data-integration/actionable-log-files.html
it says d_adsrc is Advertiser ID. 

Which one is correct?

**Comment by vgiurgiu** [comment]
Hi @weijiejane , thanks for opening this issue.

To answer your question, both definitions are OK, but not complete. 

d_adsrc is indeed **Advertiser ID**. The correct definition is `An integration code for your advertiser's data source. Note that this is not related to Audience Manager data sources`. I think that what is most misleading in the link from the definition to the Audience Manager data sources page. 

We'll remove the hyperlink and update the description in both places to include Advertiser ID _and_ the correct definition from above. 

Any other questions or issues, please let us know.

Thanks,
Victor Giurgiu
Senior Technical Writer, Audience Manager

**Comment by vgiurgiu** [comment]
Updated both referenced articles & closing the issue. Thanks again for contributing, @weijiejane .
