### ISSUE TITLE
Segment Addressable Audience and Segment Match Rate Display 0 values

### ISSUE THREAD

**Issue by JefferyTaylor0204** [AdobeDocs/audience-manager.en#10]
Issue in help/using/features/destinations/twitter-tailored-audiences.md

It should be noted that the Segment Addressable Audience and Segment Match Rate within the Destination view will not populate values. This is expected behavior because the match tables are not hosted by Adobe but rather are maintained at Twitter. 

I spoke with Terry Chen via slack and his response was:
"Terry Chen  reason we're not showing addressable audience and match rates for twitter is because the matching happens in twitter in this case"
"we don't host the match tables for twitter as we do with other destinations"

**Comment by vfalon** [comment]
Thanks for pointing this out, Jeffery. We'll update the documentation with this note.

**Comment by vfalon** [comment]
Documentation updated. Closing the issue.
