### ISSUE TITLE
Frequency ... including users who have not realized the trait (?)

### ISSUE THREAD

**Issue by TofJossic** [AdobeDocs/audience-manager.en#11]
Issue in help/using/features/segments/recency-and-frequency.md

I feel there is an issue with the wording in the Frequency Capping Examples (see below).

> _The expression frequency([1000T]) <= 5 includes all users that have realized the trait with the ID "1000" a maximum of five times, **including users who have not realized the trait**._

I understand the fact we are using Less than or equal which includes zero but to me and some customers I've had, if the trait is gathering population, I assume the trait has been realised 1 or up to 5 times so the assumption is that a trait needs to be realised to be counted. The documentation statement seems counter-intuitive and leads to confusion.

My 2 cents, hopefully we can improve this somehow - Thanks

**Comment by TofJossic** [comment]
Regarding what we understand to be 'Less than or equal which includes zero'

Customer replied:

> If that was the case, every single segment with frequency <= X, being X any number from 1 to infinity, would be huge classifying every person within the DMP. Isn’t frequency and recency supposed to be a filter of some sort?
Looking at the examples in the doc, I see the point, but still find very unjustified to do something like that. Since it’s said in the beginning of it, **that it is for traits that’s been realized only**, and it’s doing the part of a “NOT” in the segment.

**Comment by vgiurgiu** [comment]
Hey @TofJossic - thanks for contributing. We've updated the **Recency and Frequency** page to clarify that the expression ` frequency([1000T]) <= 5` is not valid and to advise which expression is valid for that use case. 

We also updated the recency part in the article to clarify what each operator (`<=`, `=>`) does.
