### ISSUE TITLE
Retain the last clicked topic as selected or keep the scroll near to the position of clicked topic.

### ISSUE THREAD

**Issue by asodhi90** [AdobeDocs/audience-manager.en#12]
Here is another feedback:
Whenever we click on any topic from left side menu, page refreshes and with that refresh my last topic-click doesn’t get retained. Which looks a bit annoying thing because again I have go all the way down or keep on opening the sub-options to reach till that specific topic which I clicked.

Change request: Retain the last clicked topic as selected or keep the scroll near to the position of clicked topic.

![image](https://user-images.githubusercontent.com/55819994/65652988-3fce1300-e031-11e9-9c82-61977a0722a2.png)

**Comment by vgiurgiu** [comment]
Hey @asodhi90 , thanks for reporting this. Unfortunately, the Audience Manager documentation team has no control over this navigational aspect of our pages. 

That being said, I can't reproduce the first part of the description: `Whenever we click on any topic from left side menu, page refreshes and with that refresh my last topic-click doesn’t get retained`. After the refresh, the last clicked topic in the TOC remains selected, so by scrolling down, you can see which page you selected. I agree though that you need to scroll down, which can be annoying.

I relayed this issue to the team that handles the UI/UX of our pages and will let you know through internal channels when there is a fix. 

Thanks!
Victor
