### ISSUE TITLE
segment Frequency Cap

### ISSUE THREAD

**Issue by cmudaliyar** [AdobeDocs/audience-manager.en#13]
Issue in help/using/features/segments/recency-and-frequency.md

At the frequency level, can we have clear comment explaining <= will also consider '0' as a frequency qualification criteria and will consider all the user? this is not clearly mentioned and ended up populating a lot of user population at the segment level.

**Comment by vgiurgiu** [comment]
Hey @cmudaliyar - thank you for reporting this issue. 

We've updated the Recency and Frequency page to clarify that the expression `frequency([1000T]) <= 5` is not valid and to advise which expression is valid for that use case.

We also updated the recency part in the article to clarify what each operator (`<=, =>`) does.

Best regards,
Victor Giurgiu
Senior Technical Writer, Audience Manager
