### ISSUE TITLE
Syntax example is maybe misleading

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/audience-manager.en#14]
Issue in help/using/integration/sending-audience-data/batch-data-transfer-explained/id-sync-file-based.md

Hi guys,
In this doc, it has filename syntax that starts with: adobe_id_ [c2c_id_] ...
I guess I thought that when you have something in square brackets, it is **optional**, which in this case would be wrong, because then you could start a file with: adobe_id_c2c_id...
Instead, it will **replace** the first part if it is PBD, right? Anyway, just wanted you guys to think about this one more time. It might just be me that would be confused by this, and on the actual PBD doc pages you give great filename examples. It's just on this page that is not specific to PBD where it might be confusing. Let me know if you have any questions.
Thanks,
Doug Moore

**Comment by vfalon** [comment]
Thanks for raising this, Doug. That's correct, in this situation, the prefix is replaced with c2c.
I've updated the docs to reflect that.

Thanks,
Vlad
