### ISSUE TITLE
False link

### ISSUE THREAD

**Issue by kantarse** [AdobeDocs/audience-manager.en#15]
The link https://admin.demdex.com/ in https://docs.adobe.com/content/help/en/audience-manager-admin/admin-guide/admin-login.html does not work. (Timeout)

**Comment by vgiurgiu** [comment]
Hi @ercanyuz  - the documentation repository you referenced is a guide for our admin interface. The link that you reported as not working, https://admin.demdex.com/, works only for Adobe employees. 

Moreover, that repository is linked to Adobe internal GIT accounts, so only Adobe employees are able to create issues for that repositories. 

Best regards,
Victor Giurgiu
Senior Technical Writer, Audience Manager
