### ISSUE TITLE
Incorrect Hyperlinks

### ISSUE THREAD

**Issue by chee-aam** [AdobeDocs/audience-manager.en#16]
Issue in help/using/reporting/audience-optimization-reports/aor-publishers/import-dfp.md

the links via google and via cookie destination, the landing URLs are swapped

**Comment by vgiurgiu** [comment]
Fixed. Thanks for reporting, @chee-aam .

**Comment by chee-aam** [comment]
NP, anytime!

Thanks,
Katelyn
Katelyn Chee  |  Audience Manager Consultant  |  Adobe  |  c. 437.225.0032  |  chee@adobe.com<mailto:chee@adobe.com>
Please make note of my upcoming business travel, vacation, and Canadian holidays:
