### ISSUE TITLE
Update Language to Indicate that all Uploaded IDs are Case-sensitive

### ISSUE THREAD

**Issue by JefferyTaylor0204** [AdobeDocs/audience-manager.en#18]
Issue in help/using/faq/faq-inbound-data-ingestion.md

The answer to the question, "Are the data file contents case-sensitive? How about the ID sync?" should include that ALL uploaded IDs are case-sensitive; not just UUID. For example CRM IDs.

-- Answer:
There are two basic components of a data file: A Unique User ID (UUID) and profile data, usually in the form of key-value pairs or codes. The UUID is case-sensitive. Generally, profile or key-value data is not case-sensitive.

**Comment by vgiurgiu** [comment]
Hi @JefferyTaylor0204 ,

Thanks for reporting this. We updated the FAQ to replace UUID with User ID and link to a page where User ID is described. This should make it clear that all User ID types are case sensitive.

Cheers,
Victor
Senior Technical Writer, Audience Manager
