### ISSUE TITLE
Table Structure Not Correct

### ISSUE THREAD

**Issue by Crossix-Product** [AdobeDocs/audience-manager.en#19]
Issue in help/using/reference/ids-in-aam.md

Looks like the top table structure was corrupted on one of the recent updates

**Comment by vfalon** [comment]
Thanks for reporting this, David! We're investigating and we'll update it.

Vlad Falon
Technical Writer, Audience Manager

**Comment by vfalon** [comment]
The table should be displayed correctly now.
Thanks again for contributing, David!

Vlad
