### ISSUE TITLE
All code samples seem to wrap across multiple lines

### ISSUE THREAD

**Issue by catacgc** [AdobeDocs/audience-manager.en#2]
Issue in help/using/api/dcs-intro/dcs-api-reference/dcs-api-methods.md

![image](https://user-images.githubusercontent.com/490592/64260400-74b7e000-cf33-11e9-8812-2452e155543c.png)

**Comment by vfalon** [comment]
Thanks for pointing this out, Cata. I'll take care of the code samples.

**Comment by vfalon** [comment]
Updated the documentation & closing the ticket.
