### ISSUE TITLE
BAAAM Folder API - Include Sub-Folders

### ISSUE THREAD

**Issue by Promatica-Consulting** [AdobeDocs/audience-manager.en#20]
Issue in help/using/reference/bulk-management-tools/bulk-management-intro.md

Can you please update the BAAAM retrieve folder to get all the sub-folders in the folder as well. Right now if I put nothing or Root. I only get the root folders, not all the sub-folders in the root and their sub-folders down to 5 branches. That is the limit AAM currently has.

The previous version only went in 4 tiers, when the limit was 5. Meaning the fifth sub-folder branch never would show up in BAAAM. So At least in that version you could figure out the sub-folders.

**Comment by vgiurgiu** [comment]
Hello and apologies for the late reply. We have an open internal ticket for this issue. Until we resolve the issue, we recommend you use the old version of BAAAM (attached to this message). 

[BAAAM_August_2018.xlsm.zip](https://github.com/AdobeDocs/audience-manager.en/files/3888286/BAAAM_August_2018.xlsm.zip)

Victor Giurgiu
Senior Technical Writer
Adobe Audience Manager

**Comment by vgiurgiu** [comment]
@Promatica-Consulting , we have a new version of BAAAM up on our site. Please check if this fixes your issue. 

Download it from https://docs.adobe.com/content/help/en/audience-manager/user-guide/reference/bulk-management-tools/bulk-management-intro.html#download

**Comment by vgiurgiu** [comment]
Closing this issue.

**Comment by Promatica-Consulting** [comment]
Thanks, sorry for the delay. The new version only goes one folder deep. What I am looking to do is when I choose the root folder it gives me a list of all the folders, all their nested folders, all the nested folder's folders, etc. Basically a complete folder structure.
