### ISSUE TITLE
The S2S fields are not listed in the correct order and are missing some fields

### ISSUE THREAD

**Issue by JefferyTaylor0204** [AdobeDocs/audience-manager.en#21]
Issue in help/using/reporting/dynamic-reports/segment-segment-overlap-report.md

Here are the fields and their order as that are actually populated in the header of an S2S overlap file:
"segment_id1","segment_name1","segment_id2","segment_name2","rangeid","datethru","segment_uniques1","segment_uniques2","overlap_uniques","Overlap_perc"

I propose that the documentation should be updated to reflect this information correctly.

**Comment by vgiurgiu** [comment]
The fields in the issue description refer to overlap files and are listed correctly here: 
https://docs.adobe.com/help/en/audience-manager/user-guide/reporting/interactive-and-overlap-reports/overlap-csv-files.html#segment-segment-records

As part of this commit, we did update the following three pages for the items in the tables to match the order in the popups in the reports:

* https://docs.adobe.com/content/help/en/audience-manager/user-guide/reporting/interactive-and-overlap-reports/trait-trait-overlap-report.html
* https://docs.adobe.com/content/help/en/audience-manager/user-guide/reporting/interactive-and-overlap-reports/segment-trait-overlap-report.html
* https://docs.adobe.com/content/help/en/audience-manager/user-guide/reporting/interactive-and-overlap-reports/segment-segment-overlap-report.html
