### ISSUE TITLE
d_rd URL needs to be Encoded Properly

### ISSUE THREAD

**Issue by JefferyTaylor0204** [AdobeDocs/audience-manager.en#22]
Issue in help/using/integration/media-data-integration/click-data-pixels.md

There is a concern that the 'd_rd' value is not properly encoded in the URL examples of:
https://client.demdex.net/event?d_event=click&d_creative=123&d_rd=http%3A%2F%2Fadobe.com%2Fcallback%3Fcreative%3D%25d_creative%25

https://client.demdex.net/event?d_event=click&d_creative=1235&d_src=203&d_campaign=4709&d_adgroup=3408&d_placement=1001&
d_rd=http%3A%2F%2Fadobe.com%2Fcallback%3Fcreative%3D%25d_creative%25%26campaign%3D%25d_campaign%25%26adgroup%3D%25
d_adgroup%25%26d_placement%3D%25placement%25%26src%3D%25d_src%25

While recently working with an adobe consultant, they above examples were leveraged and the URL redirection did not work as expected. The issue was that the d_rd was not properly encoded. It was discovered that the d_rd URL needed to be encoded a total of 2 times. For example:

d_rd=http%3A%2F%2Fadobe.com%2Fcallback%3Fcreative%3D%25d_creative%25%26campaign%3D%25d_campaign%25%26adgroup%3D%25
d_adgroup%25%26d_placement%3D%25placement%25%26src%3D%25d_src%25

becomes:

d_rd%3Dhttp%253A%252F%252Fadobe.com%252Fcallback%253Fcreative%253D%2525d_creative%2525%2526campaign%253D%2525d_campaign%2525%2526adgroup%253D%2525%0Ad_adgroup%2525%2526d_placement%253D%2525placement%2525%2526src%253D%2525d_src%2525

Using an online encoder, the URL needs to be run through the encoding process 2 times for the d_rd parameter to be properly encoded and have the redirect function properly.  

This is difficult to describe over text, you can email me or ping me in Slack if more information is needed.

**Comment by vfalon** [comment]
Thanks for reporting this, Jeffery. I've updated the docs to reflect the behavior.
