### ISSUE TITLE
Confusing warning on FTP transfers

### ISSUE THREAD

**Issue by snielson** [AdobeDocs/audience-manager.en#23]
Issue in help/using/integration/sending-audience-data/batch-data-transfer-explained/inbound-ftp-filenames.md

The warning regarding the FTP inbound not being supported is somewhat confusing / concerning to clients. Currently we still process files if they are sent to our inbound FTP endpoint (unless this changed recently??).

Could this be updated to reflect that existing FTP configurations will still continue to work for the time being?

**Comment by vfalon** [comment]
Thanks for pointing this out, Shane. We've reworded the section to make things clearer.
