### ISSUE TITLE
DTM vs Launch instructions

### ISSUE THREAD

**Issue by JMiller-Disco** [AdobeDocs/audience-manager.en#24]
It looks like much of the documentation for Audience Manager was created pre-Launch.
Looking at this section  [here](https://docs.adobe.com/content/help/en/audience-manager/user-guide/implementation-integration-guides/integration-other-solutions/audience-management-module.html) about integrating modules. It might be useful in the "Pre-Req." section to clarify that the instructions are meant for DTM implementations as versus Launch.

**Comment by JMiller-Disco** [comment]
Please consider my Pull request. I don't have enough time to read through the CLA right now, but it's an easy fix that saves confusion for people that land on a page meant for DTM integration.

**Comment by vgiurgiu** [comment]
Hi @JMiller-Disco , thanks for flagging this. I have a few comments and questions before we can merge in your pull request.

1. We'll add a note to the top of the page, mentioning that the instructions apply to integrations via DTM. However, I'd like to also point readers to instructions about forwarding Analytics data to Audience Manager using Launch. Is this the right page to link to for that - https://docs.adobe.com/content/help/en/launch/using/extensions-ref/adobe-extension/analytics-extension/overview.html#adobe-audience-manager ? 
2.  In your pull request, you mention: `Integrate DIL code through [Adobe Dynamic Tag Manager](https://marketing.adobe.com/resources/help/en_US/dtm/c_overview.html)`. However, I'd like to also link to a page that instructs users how to implement Audience Manager using DTM. Please confirm if this is the correct page - https://docs.adobe.com/content/help/en/dtm/using/tools/audiencemgmt.html.

**Comment by JMiller-Disco** [comment]
Hi @vgiurgiu ,

I'm not sure about (1):
I think in basic cases it is sufficient to use the Analytics extension in Launch with the instructions in your link, but there are more features accessible by introducing the DIL object via the Audience Manager Extension, [here](https://docs.adobe.com/content/help/en/launch/using/extensions-ref/adobe-extension/adobe-audience-manager-extension.html). I kept it generic because it depends on what a user needs from their Launch implementation.
Side-note, some of the features of the Audience Manager Module within the page being edited don't appear to be available through either of the Launch options. I would double-check, but I don't think you can set the aam_uuid cookie at all when using Launch (unless using custom code).

(2):
I think it's a similar issue where it may be too specific of a use-case. It's a pain to go through a whole guide, but it may be better to have the end-user walk themselves up to that section. That's pretty subjective though, and I'm a bit indifferent.

My goal was to keep it pretty vague/generic where to re-point someone. I think your links may be more helpful in most cases, but what drove me to these pages was reading about information on setting the aam_uuid cookie, and, only after staring at the article for a while, I realized my property was in Launch and the article wasn't relevant. It would probably be useful to see a parallel article written for Launch that could be switched between, but it would take a deep understanding of the similarities and differences between the two products--which I do not have yet.

Would you like me to update the pull request to your links? Or how should we move forward?

**Comment by vgiurgiu** [comment]
@JMiller-Disco  - we updated the page to mention that the instructions refer to DTM or any other Tag Management solution, _except_ Adobe Launch. 

After the holiday break, we'll update the page to include instructions on how to implement with Launch, DTM, or any other Tag Management solution. Closing this issue. 

Cheers!
