### ISSUE TITLE
Folder Traits are Not Supported for Use as a Conversion Trait

### ISSUE THREAD

**Issue by JefferyTaylor0204** [AdobeDocs/audience-manager.en#26]
Issue in help/using/features/audience-lab/audience-lab-manage-test-groups.md

In Item #5 on the page, it discusses Conversion Traits. A bullet point should be added to indicate that using a Folder Trait as a Conversion Trait is not supported. It will result in 0 Aggregate and Trend reporting being displayed within the test. 

Jira References:
AAM-38962
AAM-38961
AAM-38684

**Comment by vgiurgiu** [comment]
Thanks for tracking this down and creating the ticket, @JefferyTaylor0204 !

Please see the updated page https://docs.adobe.com/content/help/en/audience-manager/user-guide/features/audience-lab/audience-lab-manage-test-groups.html.
