### ISSUE TITLE
d_ and h_ keys are not found in the Signals Search Feature

### ISSUE THREAD

**Issue by JefferyTaylor0204** [AdobeDocs/audience-manager.en#27]
Issue in help/using/features/traits/trait-variable-prefixes.md

I think it is important to highlight that the d_ and h_ keys are not returned in the Signals feature. This means that if a customer is attempting to locate them in the Search function of the Signals feature, they will not successfully find them, however, if they create a trait expression that uses these keys the associated data will be captured in the AAM trait.

**Comment by vfalon** [comment]
Thanks for reporting this, Jeffery. We've updated the documentation to state that signals prefixed by d_ and h_ are not surfaced in Signals Search.

https://docs.adobe.com/content/help/en/audience-manager/user-guide/features/data-explorer/signals-search/data-explorer-search-pairs.html#excluded-signals

https://docs.adobe.com/content/help/en/audience-manager/user-guide/features/traits/trait-variable-prefixes.html
