### ISSUE TITLE
How do I access the Unused Signals report?

### ISSUE THREAD

**Issue by wilderfreed** [AdobeDocs/audience-manager.en#28]
Issue in help/using/reporting/dynamic-reports/unused-signals.md

I see information about what the unused signals report IS and what it DOES, but where can I find it? I've checked a number of different locations in AAM.

The steps for getting to this report, or where it is located, are unclear.

**Comment by vgiurgiu** [comment]
@wilderfreed - thanks for reporting this. Please see the updated page for instructions on how to find the report in the Audience Manager UI and for instructions on what to do in case you can't see the report. 

Best regards,
Victor Giurgiu
Senior Technical Writer, Audience Manager
