### ISSUE TITLE
experience cloud help pages

### ISSUE THREAD

**Issue by ravinderangelmaya** [AdobeDocs/audience-manager.en#29]
Issue in help/using/features/destinations/create-url-destination.md

hi

i recommend you improve the navigation and content for these pages e.g. https://docs.adobe.com/content/help/en/audience-manager/user-guide/features/destinations/custom-destinations/create-url-destination.html

when i navigate from left menu frame to topics; i get content but the left menu goes back to the topic of the topics menu; so have to scroll down to return to the topic i was reading.

**This is so frustrating and poor in terms of design;** you need links to stay where people were exploring instead of going up and down to pages.

This applies for all help pages using https://docs.adobe.com/

Can you rectify this navigation problem?

Also your content on some pages is vague and not always accurate

ravinder basra
![Capture](https://user-images.githubusercontent.com/44301159/73079434-1b3d5700-3ebc-11ea-820b-b331cf5507f5.JPG)

**Comment by vgiurgiu** [comment]
Hi @ravinderangelmaya ! 

First of all, thank you for your feedback and suggestions. We brought up the navigation issue with the team that administers our website and are hoping for a resolution soon. 

On your last comment, about content on some pages being vague and not always accurate, we'd like to know more. Can you please provide some examples of pages where the content didn't match your expectations? We'll do our best to update these pages in a timely manner.

Best regards,
Victor 
Senior Technical Writer, Audience Manager

**Comment by vgiurgiu** [comment]
Hi @ravinderangelmaya ,

I wanted to come back to you with some updates. Our pages will get a new look&feel in a few months, so hopefully that should solve the navigation issue you mentioned.

I am still interested in finding out which pages you think are vague and inaccurate. Please signal those and we'll do our best to update them asap.

Victor

**Comment by ravinderangelmaya** [comment]
Hi Victor

thank you.

example of vague pages :

- creating a mobile property in official launch help -
https://docs.adobe.com/content/help/en/launch/using/overview.html - none
existence; I had to visit
https://aep-sdks.gitbook.io/docs/getting-started/create-a-mobile-property
instead;
this should be in our official launch help

there are other examples; I think help pages need reauditing with new
release generally.

thank you

ravinder

**Comment by vgiurgiu** [comment]
@ravinderangelmaya  - I'll be closing this issue. We're still on track to migrate to a new platform for documentation, which will give the pages a new look&feel.

As for the Launch documentation suggestion, can you please open an issue directly on that page for the Launch team to look into it - https://docs.adobe.com/content/help/en/launch/using/overview.html ? 

Thanks for contributing!
Victor
