### ISSUE TITLE
Facebook WCA integration no longer working

### ISSUE THREAD

**Issue by snielson** [AdobeDocs/audience-manager.en#3]
https://docs.adobe.com/help/en/audience-manager/user-guide/implementation-integration-guides/integrating-third-party/facebook-wca-integration.html

I believe this documentation page should be removed or not made public, as Facebook no longer allows this integration. The following comment was made by a FB rep

"Adobe is onboarding cookie-based audiences to our platform by passing segment_id as a custom parameter in the Facebook pixel. We also believe this DMP is building cross-publisher audiences by firing a single Facebook pixel across multiple websites. Both of these approaches violate our Facebook Business Tools Terms. We have contacted the DMP regarding this violation. The previous form of the ‘hack’ has been completely removed. At this time, there are no plans for a resolution on the roadmap."

**Comment by vgiurgiu** [comment]
Closing this issue, FB reassured the product team that the integration is working. 
Thanks for flagging this, @snielson.
