### ISSUE TITLE
Feeds are limited to a Single Data Source.

### ISSUE THREAD

**Issue by jeftaylor79** [AdobeDocs/audience-manager.en#30]
Issue in help/using/features/audience-marketplace/marketplace-data-providers/marketplace-create-manage-feeds.md

It should be better highlighted that a Feed is limited to a single data source, it cannot have multiple data sources within a single feed.

**Comment by vfalon** [comment]
Thanks for raising this, Jeffery!
I've updated the documentation to reflect this aspect.

"Select a data source from the Data Source options. Data feeds are limited to a single data source. You cannot assign multiple data sources to the same data feed. "
