### ISSUE TITLE
PMR related update to Segment Builder page

### ISSUE THREAD

**Issue by chee-aam** [AdobeDocs/audience-manager.en#31]
Issue in help/using/features/segments/segment-builder-data.md

Hi there, 

I confirmed with Ben and this page: https://docs.adobe.com/content/help/en/audience-manager/user-guide/features/segments/segment-builder-data.html under this section: 
**Segment Population Data for Merge Rules With a Device Graph Option**

in the **definition** it references: 

...with up to _3-other device profiles_... 

for both **Real-Time Population (Existing)** and **Real-Time Population (Existing)** Metric's definition.  

3-other devices should be replaced with 100-other devices

**Comment by vfalon** [comment]
Thanks for reporting this! We've updated the documentation to reflect the change.
