### ISSUE TITLE
BAAAM Folder API - Include Sub-Folders

### ISSUE THREAD

**Issue by Promatica-Consulting** [AdobeDocs/audience-manager.en#33]
This is related to issue #20. The new version only goes one folder deep. What I am looking to do is when I choose the root folder it gives me a list of all the folders, all their nested folders, all the nested folder's folders, etc. Basically I want to get a complete folder structure.

**Comment by Promatica-Consulting** [comment]
Wanted to bump this topic and see if there is any fix?

**Comment by vgiurgiu** [comment]
Hi @Promatica-Consulting  - apologies, we missed this issue. 

We have a new BAAAM version out, but I don't think it addresses the issue you're having. Just to clarify, are you using the latest version -  `BAAAM_V2_20200311.xlsm`?

If not, you can get that version here - https://docs.adobe.com/content/help/en/audience-manager/user-guide/reference/bulk-management-tools/bulk-management-intro.html#download

Let us know if you're still having trouble using the latest version and we'll file an enhancement request with Product Management on your behalf.

**Comment by Promatica-Consulting** [comment]
No worries, I just downloaded the latest version and the issue still is there. 

As you can see in this screen shot, the Baaam Tool only goes one folder deep into the folder tree. I would like it to return the whole folder tree when I put 0 or leave it blank
![BAAAM_Tool_ScreenShot](https://user-images.githubusercontent.com/56885594/79239156-d62f1e00-7e35-11ea-8829-bd65ca9c98c2.png)

This screenshot shows the AAAM account goes deeper than 1 subfolder
![AAAM_ScreenShot](https://user-images.githubusercontent.com/56885594/79239297-04acf900-7e36-11ea-8d23-61b4fbd5b6c2.png)

I can't use the old baaam tool because it only goes 4 folders deep. AAAM allows up to 5 folders deep.

**Comment by vgiurgiu** [comment]
This is very helpful, thank you. We'll relay your request to Product Management. One more question - were you, at some point, using an older BAAAM version that allowed you to see 5 folders deep?

Basically, was the functionality you're requesting present in an older version of BAAAM?

**Comment by Promatica-Consulting** [comment]
No, at the time the older one was created you could only go 4 folders deep within the AAM platform. I haven't looked at the old baaam's macros in a while, but if my memory is correct they didn't use a loop just repeated the code 4 times. That is how I found out there was a new version of baaam and this new folder request.

**Comment by vgiurgiu** [comment]
Got it. Well, we'll relay all this to our Product Management team as an enhancement request. Let's keep this issue open and we'll get back to you here with updates once we have some. 

Best regards,
Victor
Senior Technical Writer, Audience Manager

**Comment by vgiurgiu** [comment]
@Promatica-Consulting  - one more question - can you please let us know your **company name** in Audience Manager? I couldn't find anything when searching by `Promatica consulting`. 

Thank you!
Victor

**Comment by Promatica-Consulting** [comment]
The one I referenced in the screenshot above is AMERICAN LEBANESE SYRIAN ASSOCIATED CHARITIES, but it doesn't matter the instance it happens across all accounts.

**Comment by vgiurgiu** [comment]
Thanks, to add more weight and help prioritize the enhancement request, can you please send us the company names of more accounts you manage? 

Feel free to send this information to me directly over email at: `giurgiu[at]adobe[dot]com`

Best regards,
Victor

**Comment by Promatica-Consulting** [comment]
Of course, AMERICAN LEBANESE SYRIAN ASSOCIATED CHARITIES (St. Jude) is the one I was referring to, but it happens to all accounts.

Cheers,
Colin

[photo]
Colin DiBiase
Chief Data Solutions Architect

c 520-241-3795
www.promaticaconsulting.com<http://www.promaticaconsulting.com/>
Click Here to Book a Mtg<https://outlook.office365.com/owa/calendar/Promatica@promaticaconsulting.com/bookings/>

[cid:image002.jpg@01D614B1.432BA8F0]<http://www.facebook.com/promatica>
[cid:image003.jpg@01D614B1.432BA8F0]<http://www.linkedin.com/company/promatica-consulting?trk=company_logo>
[cid:image004.jpg@01D614B1.432BA8F0]<http://twitter.com/promaticaadvise>

**Comment by vgiurgiu** [comment]
@Promatica-Consulting  - Hi, Colin. Just an FYI that I didn't get any email from you (see my previous comment). At your convenience, please send an email so we can submit an enhancement request. 

Thanks,
Victor

**Comment by vgiurgiu** [comment]
@Promatica-Consulting  - We uploaded a new Bulk Management worksheet today. 

See https://docs.adobe.com/content/help/en/audience-manager/user-guide/documentation-updates/docs-2020.html#aam-may-updates for all the updates we made to the worksheet. 

Let us know please if this fixes the troubles you've been having.

Best regards,
Victor

**Comment by vgiurgiu** [comment]
Looks like the new worksheet solved the issue. Closing the issue, please reopen if needed.
