### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by rishimittal2003** [AdobeDocs/audience-manager.en#34]
Issue in help/using/overview/data-security-and-privacy/data-privacy-consent.md

Links to Experience Cloud Opt-in Service not working

**Comment by vgiurgiu** [comment]
Hey @rishimittal2003  - thanks for flagging this. We'll fix the links soon. Until then, here is the link to the Experience Cloud Opt-in Service:

https://docs.adobe.com/content/help/en/id-service/using/implementation/opt-in-service/optin-overview.html

**Comment by vgiurgiu** [comment]
Fixed. Closing the issue.
