### ISSUE TITLE
Screenshot is old for Data Source settings

### ISSUE THREAD

**Issue by ankurmehrotra** [AdobeDocs/audience-manager.en#35]
Issue in help/using/features/traits/client-activity-synced-audience-traits.md

>> The screen shot displayed on the help page does not match with the application anymore.

Current Image: https://docs.adobe.com/content/dam/help/audience-manager.en/help/using/features/traits/assets/datasource_synced.png
Expected: 
![Data Synced trait](https://user-images.githubusercontent.com/15048072/84593118-a35fd100-ae4a-11ea-995b-dab26003c8ff.png)

**Comment by vfalon** [comment]
Thanks for reporting this, Ankur!

We've updated the screenshot and it should be visible on the page later today.
Looking forward to even more contributions from your side.

Have a great day!

Vlad Falon
Audience Manager Senior Technical Writer
