### ISSUE TITLE
Incorrect information on "Match Rate Considerations" 

### ISSUE THREAD

**Issue by snielson** [AdobeDocs/audience-manager.en#36]
Issue in help/using/features/destinations/twitter-tailored-audiences.md

Under "Match Rates Considerations"
- When using Twitter Tailored Audiences, the Segment Addressable Audience and Segment Match Rate metrics from the destination page will not display any values. This is normal behavior, since audience matching along with the match rates for this destination are handled and hosted by Twitter, not Adobe.

This no longer applies, as destinations exporting out UUIDs should now show 100% in match rates.
See JIRA [AAM-51615](https://jira.corp.adobe.com/browse/AAM-51615) for this change.

**Comment by vfalon** [comment]
Thanks for pointing this out, Shane!
I've removed that part from the considerations.

Vlad
