### ISSUE TITLE
Wrong Google  information

### ISSUE THREAD

**Issue by carlostnadobe** [AdobeDocs/audience-manager.en#37]
Issue in help/using/features/destinations/device-based-destinations-list.md

There in a item for Google in the list that is wrong (or at least confusing):

Google AdsWords Display | 02/08/2018 | Real-time | Yes | Yes | No | Yes
-- | -- | -- | -- | -- | -- | --

We do not have any S2S integration with Adwords product, since this destination is made via URL destination (https://wiki.corp.adobe.com/display/MCPI/Google+-+AAM+Destination).

The only S2S destination we have with Google, is not for Adwords, but for Google (DBM, DFP, DFP Premium). - https://wiki.corp.adobe.com/display/MCPI/Google+-+AAM+Destination

**Comment by vfalon** [comment]
Hi Carlos,

Thanks for reporting this. I've removed the AdWords ddestination from the list.
Thanks for contributing!

Vlad Falon
Senior Technical Writer
Audience Manager
