### ISSUE TITLE
Confusing terminology

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/audience-manager.en#40]
Issue in help/using/integration/sending-audience-data/batch-data-transfer-explained/inbound-ftp-filenames.md

In the documentation it refers to DPID which looks like it's referring to the single customer ID (PID). However Jess and others are saying that it actually refers to the Data Source ID. Can this be clarified? There's the same issue in the S3 page as well. 

Thanks,
Jonathan

**Comment by vgiurgiu** [comment]
Hi @jweissba  - we reached out to our Engineering team and will post a response here and update the documentation to clarify the `PID` vs. `DPID` question as soon as possible.

**Comment by vgiurgiu** [comment]
Hi @jweissba - I can confirm that PID is **not** part of inbound file names. Jess is correct and we refer to Data Source ID in the documentation. 

We'll update the documentation and follow up on this thread once we do that.

**Comment by vgiurgiu** [comment]
@jweissba  - we have now made further updates to:

* [Amazon S3 Name and File Size Requirements for Inbound Data Files](https://docs.adobe.com/content/help/en/audience-manager/user-guide/implementation-integration-guides/sending-audience-data/batch-data-transfer-process/inbound-s3-filenames.html) 
* [FTP Name and File Size Requirements for Inbound Data Files](https://docs.adobe.com/content/help/en/audience-manager/user-guide/implementation-integration-guides/sending-audience-data/batch-data-transfer-process/inbound-ftp-filenames.html)

Following a review with the Engineering team, we updated the `DPID` and `DPID_TARGET_DATA_OWNER` fields in both articles with new definitions and clearer examples. 

Closing this ticket. Please reopen if further updates are needed.

Best,
Victor
