### ISSUE TITLE
Update documentation with new FTPs

### ISSUE THREAD

**Issue by ghost** [AdobeDocs/audience-manager.en#42]
Issue in ./help/using/integration/sending-audience-data/batch-data-transfer-explained/inbound-ftp-filenames.md

Hi team,

According to ENG we're updating the FTPs servers:

https://jira.corp.adobe.com/browse/AAM-55980?focusedCommentId=22361166&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22361166

Can we update the documentation so customers are aware of it?

**Comment by vfalon** [comment]
FTP IPs updated in this doc: https://experienceleague.adobe.com/docs/audience-manager/user-guide/faqs/faq-data-collection.html.
