### ISSUE TITLE
Specifications on the use cases

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/audience-manager.en#47]
Issue in ./help/using/features/audience-marketplace/marketplace-data-buyers/marketplace-data-buyers.md

It's not an issue but a suggestion.
It would be worth to add some specification when the customer is actually charged for cost in each use case.
For example, in the Modeling use case, he is charged when he run a model or when he activate the result of the model?

**Comment by vfalon** [comment]
Thanks for the suggestion, @angeli-adobe ! I'll make sure to add a clarification about this.

**Comment by vfalon** [comment]
Hi @angeli-adobe . Billing is based on ad impressions which need to be reported monthly. For the Modeling use case, if a customer runs a model but does not activate it, then no usage is reported. I've added this note to https://experienceleague.adobe.com/docs/audience-manager/user-guide/features/audience-marketplace/audience-marketplace-for-data-buyers/marketplace-buyer-billing.html?lang=en#case-3%3A-segments-with-modeling-and-activation-use-cases.
