### ISSUE TITLE
Code Implementation section

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/audience-manager.en#49]
Issue in ./help/using/integration/implement-audience-manager.md

The section of this page for "Code Implementation" has no instructions as to how to implement the code or links to resources showing how to do so. Can these be added?

**Comment by vfalon** [comment]
Thanks for raising this @dwright-adobe . The article is rather stale, since we now recommend the DIL implementation through Adobe Launch. I've updated that section to link to the correct DIL article.
