### ISSUE TITLE
"destination" word repeated twice

### ISSUE THREAD

**Issue by jay-nike** [AdobeDocs/audience-manager.en#55]
Issue in ./help/using/features/data-export-controls.md
Under Overview, the 2nd bullet point "Sending any data to a destination destination has a data export label that is blocked by a data export control on any of:" here the word 'destination' is repeated twice.
![image](https://user-images.githubusercontent.com/110047283/181044454-8bd123b8-1c02-484a-be92-3b2a97d08605.png)

**Comment by vgiurgiu** [comment]
@jay-nike - thanks for flagging this! We updated the sentence you highlighted: https://experienceleague.adobe.com/docs/audience-manager/user-guide/features/data-export-controls.html 

Thanks and let us know if you come across anything else!
