### ISSUE TITLE
Customer Addressable Audience instead of Addressable Audience Match Rate

### ISSUE THREAD

**Issue by jay-nike** [AdobeDocs/audience-manager.en#57]
Issue in ./help/using/features/addressable-audiences.md

I think the definition name is changed here. PFA screen shot
![image](https://user-images.githubusercontent.com/110047283/181206523-d4c70d8e-e369-4f87-9cab-a024da613ee4.png)

**Comment by vfalon** [comment]
Thanks for raising this! We've updated the definition name to reflect the diagram.
