### ISSUE TITLE
There is a full stop in 2.000, it should be 2,000 or 2000

### ISSUE THREAD

**Issue by jay-nike** [AdobeDocs/audience-manager.en#59]
Issue in ./help/using/features/traits/manage-folder-traits.md

PFA screenshot. It looks like its 2 folders, not 2000. 
![image](https://user-images.githubusercontent.com/110047283/181720153-cf1ddc8e-fe96-4a95-8d7e-690460be004d.png)

**Comment by vfalon** [comment]
Thank you for raising this. We've updated the documentation with the correct formatting.
