### ISSUE TITLE
Wrong PMR Rule details?

### ISSUE THREAD

**Issue by mugdoor** [AdobeDocs/audience-manager.en#6]
Issue in help/using/features/destinations/people-based-destinations-workflow-authenticated.md

In this file, in Step 3 (PMR), #3, it says to use the "All Cross-Device Profiles", but i thought that was only for the Offline Only use case. Shouldn't this one say Current or Last, which is shown in the screenshot?

Thanks,
Doug Moore

**Comment by vfalon** [comment]
Thanks for pointing this out, Doug! That's correct, we'll update the documentation accordingly.
