### ISSUE TITLE
Misleading sentence

### ISSUE THREAD

**Issue by angeli-adobe** [AdobeDocs/audience-manager.en#61]
Issue in ./help/using/integration/integration-aep/aam-aep-audience-sharing.md

The introductory statement is misleading (I've received this feedback from a couple of customers): 
> The audience sharing functionality between Audience Manager and Adobe Experience Platform allows you to share your Audience Manager traits and segments to Adobe Experience Platform and vice-versa. You need the [Audience Manager Connector](https://experienceleague.adobe.com/docs/experience-platform/sources/connectors/adobe-applications/audience-manager.html?lang=en) to enable audience sharing between Audience Manager and Adobe Experience Platform.

It seems that the Audience Manager Connector is needed to share data from AAM to AEP and also for AEP to AAM. But this is not the reality.
Can you please clearly specify what is needed to setup the 2 different flows:
- AAM > AEP
- AEP > AAM?
in 2 different paragraphs?

**Comment by vgiurgiu** [comment]
@angeli-adobe - thank you for reporting this! 

We worked with Engineering and Product Management to improve the Audience Manager <-> Experience Platform audience sharing document. 

Please see the new section **Get started - How to enable data sharing between Audience Manager and Experience Platform** and its two subsections, each one explaining how to enable data sharing from one app to the other:

https://experienceleague.adobe.com/docs/audience-manager/user-guide/implementation-integration-guides/integration-experience-platform/aam-aep-audience-sharing.html?lang=en#enable-data-sharing-aam-aep

Closing the issue. Let us know please if you need more information.

**Comment by angeli-adobe** [comment]
Thanks @vgiurgiu great improvement, but I think it is in the wrong paragraph. 
As a user, my expectation is to have this sentence:
![image](https://user-images.githubusercontent.com/72991519/195365134-48b2c502-f9cc-4b77-96cf-c3b05cd96db6.png)

Under this section:
![image](https://user-images.githubusercontent.com/72991519/195365229-5999ff5f-ea25-4589-ac67-4cfc533f8959.png)

Because if I'm interested in the AEP to AAM, I'll skip the paragraph AAM to AEP and jump directly there.
Hope this make sense.

**Comment by vgiurgiu** [comment]
@angeli-adobe  - good point! I rearranged the content a bit to have two clear sections: 

1. AAM -> AEP, with information on how to enable data sharing and how to use the data that is coming over
2. AEP -> AAM, with information on how to enable data sharing and how to use the data that is coming over

See the updated page here:
https://experienceleague.adobe.com/docs/audience-manager/user-guide/implementation-integration-guides/integration-experience-platform/aam-aep-audience-sharing.html

**Comment by angeli-adobe** [comment]
Wow! That's great! Thanks @vgiurgiu !
