### ISSUE TITLE
Campaign Manager can no longer be configured as outlined in this doc

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/audience-manager.en#62]
Issue in ./help/using/reporting/audience-optimization-reports/aor-advertisers/import-dcm.md

On Feb 16, 2023, Google made a change and the steps on this page that outline how to grant access to a Google Cloud Storage account using a group no longer work. See the KCS article that I created here:

https://experienceleague.adobe.com/docs/experience-cloud-kcs/kbarticles/KA-21633.html?lang=en

We need to adjust the instructions to be more in line with the Ad Manager documentation:

https://experienceleague.adobe.com/docs/audience-manager/user-guide/reporting/audience-optimization-reports/audience-optimization-publishers/import-dfp.html?lang=en

While support works with the customer to iron out any specific details, we need to work on these updates. Would it be possible to get a new draft that we can adjust while we work through the first few customers that have to make this change?

**Comment by vfalon** [comment]
Closing as discussed with @dhwoolsey.
