### ISSUE TITLE
Sending an email is no longer the approved way of logging a case with Customer Care

### ISSUE THREAD

**Issue by dhwoolsey** [AdobeDocs/audience-manager.en#63]
Issue in ./help/using/reporting/audience-optimization-reports/aor-publishers/import-dfp.md

Step 6 in the table needs to be updated and the email temple section needs to be removed (or at least heavily adjusted). When customer need to create a case with Customer Care, then the best method of doing so is outlined on this page:

https://experienceleague.adobe.com/docs/customer-one/using/home.html

I'd recommend sending them to that link or putting in a sentence or two about going to their Admin Console and logging a case. Please let me know if I can provide more details!

**Comment by vfalon** [comment]
Thank you for submitting this issue. We will review the documentation and make the necessary updates as quickly as possible. Tracking internally in AAM-62403.

**Comment by vfalon** [comment]
Documentation updated. Closing this issue.
