### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by kantarse** [AdobeDocs/audience-manager.en#7]
Issue in help/using/integration/receiving-audience-data/receiving-audience-data-overview.md

Links are wrong.

**Comment by vgiurgiu** [comment]
Hey @ercanyuz , thanks for logging this. Can you tell me what you mean by links are wrong, please?
All three links on the page are working links. 

Do you mean that the links are confusing and we should point to somewhere else from this page? To clarify, by "receiving audience data", we mean the process by which you receive data _from 
Audience Manager _  in your preferred destination.

See also, [Sending Audience Data](https://docs.adobe.com/content/help/en/audience-manager/user-guide/implementation-integration-guides/sending-audience-data/send-audience-data.html) for descriptions and specifications how to import your data _into Audience Manager_.

Thanks again for contributing & looking forward to your response,
Victor
Senior Technical Writer, Audience Manager

**Comment by kantarse** [comment]
Hi @vgiurgiu, apparently the page was edited 4 days ago and the links were corrected. See https://github.com/AdobeDocs/audience-manager.en/commit/f287244b2198eb72287359e2105d9014dd960cfb#diff-3423cb9e435ad0a1a5c4fdef071268d8
