### ISSUE TITLE
Insufficient specification

### ISSUE THREAD

**Issue by kantarse** [AdobeDocs/audience-manager.en#8]
Issue in help/using/integration/receiving-audience-data/real-time-outbound-transfers/real-time-outbound-transfers.md

There is no information about how the request should look like. Only the response is specified.

**Comment by vfalon** [comment]
Thanks for pointing this out. We're investigating and will update the documentation.

**Comment by vfalon** [comment]
We've updated the documentation to better reflect the specification.
Thanks again for reporting this.

Vlad Falon
Technical Writer
Adobe Audience Manager
