### ISSUE TITLE
Screenshot out of date for integration page

### ISSUE THREAD

**Issue by jweissba** [AdobeDocs/audience-manager.en#9]
Issue in help/using/integration/integration-other-solutions/aam-target-integration.md

Hi,
The screenshot on the page above is out of date. A customer had issues confirming the integration because his page didn't look like the screenshot. Could you update it?

Thanks,
Jonathan

**Comment by vgiurgiu** [comment]
Hey @jweissba  - thanks for opening this issue. We're working on getting a new screenshot.

**Comment by vgiurgiu** [comment]
@jweissba - we updated the screenshot in the article to reflect how Audience Manager segments appear in Target. Thanks for contributing!

Victor
